---
name: Release

on:
  release:
    types: [published]

jobs:
  release-dev:
    permissions:
      actions: read
      contents: write
      packages: write
    uses: ./.github/workflows/release-dev.yml
    with:
      app_name: wardend
    secrets: inherit
